config/routes.rb
Rails.application.routes.draw do

	root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, shallow: true
    resources :reviews, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true 
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<%= cl_image_tag("cocktail.jpg", :height=>720, :quality=>100, :width=>1420, :crop=>"scale") %>

<% @cocktails.each do |cocktail| %>
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<% cl_image_tag(cocktail.photo,
    width: 400, height: 300, crop: :fill) %>);">
  <div class="card-category"></div>
  <div class="card-description">
    

    
    
    <h2><%= cocktail.name  %></h2>
  </div>
  <%= link_to '', cocktail_path(cocktail), {:class=>"ui-button-text button_text"} %>
  <a class="card-link" href="#" ></a>
</div>
<% end  %>




<ul>
  <% @cocktails.each do |cocktail| %>
  <li>
    <%= cl_image_tag(cocktail.photo,
    width: 400, height: 300, crop: :fill) %>
    <%= link_to cocktail.name, cocktail_path(cocktail)  %>
  </li>
  <% end  %>
  <%= link_to 'create cocktail', new_cocktail_path  %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>